### ISSUE TITLE
强制在每一页面进行数学公式渲染

### ISSUE THREAD

**Issue by baoduoxu** [HiNinoJay/hexo-theme-A4#121]
每一篇文章都要在 `front-matter` 前加 `mathjax: true` 有点太麻烦了(因为之前用的其他主题写过很多文章都没加), 而且 mathjax 的配置项中
```
mathjax:
  tags: none # or 'ams' or 'all'
  single_dollars: true # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9 # relative CJK char width
  normal_width: 0.6 # relative normal (monospace) width
  append_css: true # add CSS to pages rendered by MathJax
  every_page: true # if true, every page will be rendered by MathJax regardless the `mathjax` setting in Front-matter
```
里面是有 every_page 这一强制让每一个页面都用 mathjax 渲染的选项的 (不过这里改成 true 也没啥用就是了), 不知道能不能添加这一功能, 还是说本来能实现这个功能但我哪里没配置好? 

------

什么时候能换其他英文字体(
