### ISSUE TITLE
🤔️常见问题

### ISSUE THREAD

**Issue by HiNinoJay** [HiNinoJay/hexo-theme-A4#14]
### 我的markdown代码块怎么没渲染？

答：检查你的_config.yml文件，将hexo自带的highlight和prismjs设置为false。
```yml
highlight:
  enable: false 
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false 
  preprocess: true
  line_number: true
  tab_replace: ''
```
**A4 v1.8.5版本已解决该问题，无需再做以上操作，记得恢复_config.yml为默认配置**
