### ISSUE TITLE
字体: 能否使用CDN替换字体包

### ISSUE THREAD

**Issue by xinzhizhu510** [HiNinoJay/hexo-theme-A4#183]
https://chinese-font.netlify.app/zh-cn/fonts/lxgwwenkai/LXGWWenKai-Regular
在网字计划中提供了当前使用的字体CDN，能否关闭项目中的字体引用使用CDN，目前在配置文件中关闭字体好像还是会加载字体文件，导致网站一直处于加载中的状态

**Comment by HiNinoJay** [comment]
好的，下一个版本更新

**Comment by HiNinoJay** [comment]
抱歉这么久才回复，我刚刚本地在实验`_config.a4.yml`修改配置，关闭霞鹜文楷字体：
```yml
# A4默认中文使用霞鹜文楷，如果你想关闭这种字体，首先保证enable为 true 接着可以开关对应字体
font:
  enable: true # 是否使用字体开关功能
  LXGWWenKai: false # 霞鹜文楷 如果关闭，中文则使用的是 思源宋体，思源宋体不提供关闭 
```
然后`hexo s`启动网页，发现并没有加载`LXGWWenKai-Regular`，另外，https://chinese-font.netlify.app/zh-cn/fonts/lxgwwenkai/LXGWWenKai-Regular 似乎在报500的错...

我再看看吧～
