### ISSUE TITLE
代码行不显示、 超出宽度问题

### ISSUE THREAD

**Issue by hi-nikola** [HiNinoJay/hexo-theme-A4#52]
代码行不显示、 超出宽度问题，请问这是怎么回事？
![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/52887883/97619547-11ac-465f-98f2-7bac7c570b65)

**Comment by hi-nikola** [comment]
有的代码行是黑色 有的却不显示。在用其他主题时代码行显示正常

**Comment by HiNinoJay** [comment]
### 我的markdown代码块怎么没渲染？

答：检查你的_config.yml文件，将hexo自带的highlight和prismjs设置为false。
```yml
highlight:
  enable: false 
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false 
  preprocess: true
  line_number: true
  tab_replace: ''
```
