### ISSUE TITLE
代码块怎么没有渲染？

### ISSUE THREAD

**Issue by HiNinoJay** [HiNinoJay/hexo-theme-A4#99]
### 我的markdown代码块怎么没渲染？

答：检查你的_config.yml文件（注意不是A4的配置文件），将hexo自带的highlight和prismjs设置为false。
```yml
highlight:
  enable: false 
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false 
  preprocess: true
  line_number: true
  tab_replace: ''
```

经A4使用者测试：hexo-blog-encrypt插件可能会与代码块渲染冲突，禁用插件后可以正常显示代码块，我目前暂时使用hexo-hide-posts插件暂时隐藏文章（-，-）

**A4 1.8.5版本已解决代码块渲染问题，无需再做以上操作**
